"**":
  push:
    - imports:
        - https://cnb.cool/ttf248/tokens/-/blob/main/env.yml
      stages:
        - name: sync to github
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/ttf248/lol-helper.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}
            branch: ${CNB_BRANCH}
            force: true

  web_trigger_sync:
    - imports:
        - https://cnb.cool/ttf248/tokens/-/blob/main/env.yml
      stages:
        - name: sync to github
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/ttf248/lol-helper.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}
            branch: ${CNB_BRANCH}
            force: true
